// data.jsx — Defenders, enemies, maps, waves
// Loaded as Babel script; exports go to window for shared scope.

const DEFENDERS = [
  {
    id: 'greeter',
    name: 'The Greeter',
    role: 'melee',
    roleLabel: 'MELEE',
    color: '#E63946',
    cost: 80,
    damage: 35,
    range: 70,
    rate: 1.1, // attacks per second
    splash: 0,
    slow: 0,
    flavor: 'Stands by the door. Vigorous handshake. Will not let go.',
    ability: 'Aggressive Welcome — locks one enemy in place for 0.4s and slaps them with a high-damage hello.',
    accent: '👋',
    bodyColor: '#E63946',
    hairColor: '#3a2a1a',
  },
  {
    id: 'hypeman',
    name: 'The Hype-Man',
    role: 'melee',
    roleLabel: 'FAST MELEE',
    color: '#FF3D7F',
    cost: 110,
    damage: 8,
    range: 75,
    rate: 4.0,
    splash: 0,
    slow: 0,
    flavor: 'High-fives at the speed of caffeine. "LET\u2019S GOOOO!"',
    ability: 'Rapid Fives — fastest attack rate in the game. Wears down swarms.',
    accent: '🙌',
    bodyColor: '#FF3D7F',
    hairColor: '#1A1A1A',
  },
  {
    id: 'handout',
    name: 'The Handout Giver',
    role: 'ranged',
    roleLabel: 'RANGED',
    color: '#3D5A80',
    cost: 100,
    damage: 18,
    range: 150,
    rate: 1.4,
    splash: 0,
    slow: 0,
    flavor: 'Has six different bulletins. You will take all of them.',
    ability: 'Bulletin Toss — reliable medium-range projectile. The all-rounder.',
    accent: '📄',
    bodyColor: '#3D5A80',
    hairColor: '#5a4a3a',
  },
  {
    id: 'coffee',
    name: 'The Coffee Tosser',
    role: 'ranged',
    roleLabel: 'SPLASH',
    color: '#7B5EA7',
    cost: 160,
    damage: 22,
    range: 130,
    rate: 0.85,
    splash: 50,
    slow: 0.35,
    flavor: 'Decaf? In THIS economy? Hurls hot coffee with prejudice.',
    ability: 'Donut Bomb — area damage and slows everyone in the splash zone.',
    accent: '☕',
    bodyColor: '#7B5EA7',
    hairColor: '#1A1A1A',
  },
  {
    id: 'talker',
    name: 'The Talker',
    role: 'cc',
    roleLabel: 'CONTROL',
    color: '#7B5EA7',
    cost: 90,
    damage: 0,
    range: 60,
    rate: 1.0,
    splash: 0,
    slow: 0.85,
    flavor: '"How was your week?" Forty minutes later, you still have not escaped.',
    ability: 'Trapped In Conversation — stops enemies cold. Zero damage. Maximum awkward.',
    accent: '💬',
    bodyColor: '#52B788',
    hairColor: '#9a6a3a',
  },
  {
    id: 'usher',
    name: 'The Usher',
    role: 'cc',
    roleLabel: 'CONTROL',
    color: '#3D5A80',
    cost: 130,
    damage: 6,
    range: 110,
    rate: 0.7,
    splash: 0,
    knockback: 40,
    flavor: 'Holds the rope. "Sir, the back row is full." Pushes you backward. With love.',
    ability: 'Velvet Rope — knockback on hit. Resets enemy progress on the path.',
    accent: '🪢',
    bodyColor: '#3D5A80',
    hairColor: '#1A1A1A',
  },
  {
    id: 'soundbooth',
    name: 'Sound Booth Guy',
    role: 'support',
    roleLabel: 'BUFFER',
    color: '#FFD23F',
    cost: 140,
    damage: 0,
    range: 130,
    rate: 0,
    buff: { type: 'attackSpeed', mult: 1.5 },
    flavor: 'Up in the booth. Cranks the playlist. Everyone fights faster.',
    ability: 'Hype Mix — boosts attack speed of all defenders in range by 50%.',
    accent: '🎚️',
    bodyColor: '#FFD23F',
    hairColor: '#3a2a1a',
  },
  {
    id: 'snackrunner',
    name: 'The Snack Runner',
    role: 'support',
    roleLabel: 'BUFFER',
    color: '#FFD23F',
    cost: 120,
    damage: 0,
    range: 140,
    rate: 0,
    buff: { type: 'damage', mult: 1.4 },
    flavor: 'Hands out goldfish crackers like ammo. Friendly fire is real.',
    ability: 'Snack Boost — defenders in range deal 40% more damage.',
    accent: '🥨',
    bodyColor: '#52B788',
    hairColor: '#1A1A1A',
  },
  {
    id: 'organizer',
    name: 'The Organizer',
    role: 'special',
    roleLabel: 'ECONOMY',
    color: '#FF3D7F',
    cost: 150,
    damage: 0,
    range: 0,
    rate: 0,
    income: 18, // spirit per 5s
    flavor: 'Has a clipboard. Has a SECOND clipboard. Generates Community Spirit just by existing.',
    ability: 'Paperwork — generates +18 Community Spirit every 5 seconds. Buy more friends.',
    accent: '📋',
    bodyColor: '#FF3D7F',
    hairColor: '#5a4a3a',
  },
  {
    id: 'pk',
    name: 'The Pastor\u2019s Kid',
    role: 'special',
    roleLabel: 'ULTIMATE',
    color: '#1A1A1A',
    cost: 320,
    damage: 80,
    range: 200,
    rate: 0.6,
    splash: 110,
    flavor: 'Has the keys. Knows the basement code. Has been here since birth.',
    ability: 'Insider Knowledge — massive AOE damage. Resolves crowds in one swing.',
    accent: '🗝️',
    bodyColor: '#1A1A1A',
    hairColor: '#1A1A1A',
  },
];

const ENEMIES = {
  potluck: {
    id: 'potluck',
    name: 'Potluck Pirate',
    hp: 45,
    speed: 38,
    bounty: 14,
    damage: 1,
    color: '#F77F00',
    hat: 'plate',
    flavor: 'Coming for the casserole.',
  },
  late: {
    id: 'late',
    name: 'Late Arrival',
    hp: 30,
    speed: 60,
    bounty: 10,
    damage: 1,
    color: '#3D5A80',
    hat: 'jacket',
    flavor: '"Was service at 10 or 10:30?"',
  },
  vbs: {
    id: 'vbs',
    name: 'VBS Sugar Kid',
    hp: 18,
    speed: 95,
    bounty: 7,
    damage: 1,
    color: '#FFD23F',
    hat: 'cone',
    flavor: 'Ate three juice boxes. Cannot be stopped by reason.',
  },
  asker: {
    id: 'asker',
    name: 'Question Asker',
    hp: 70,
    speed: 28,
    bounty: 18,
    damage: 2,
    color: '#7B5EA7',
    hat: 'glasses',
    flavor: '"So in Leviticus 23..."',
  },
  boss: {
    id: 'boss',
    name: 'The Committee',
    hp: 700,
    speed: 22,
    bounty: 120,
    damage: 5,
    color: '#1A1A1A',
    hat: 'crown',
    flavor: 'Five people. One opinion. Many sub-points.',
    boss: true,
  },
};

// Path is in stage-canvas coordinates (1280x800). Game area ~ 1280x640 (HUD eats 160 top).
const MAPS = [
  // Path is in stage-canvas coordinates (1280x800). Path lies within ~1280x720 to leave HUD room.
  {
    id: 'lobby',
    name: 'The Lobby',
    subtitle: 'where it all begins',
    difficulty: 1,
    unlocked: true,
    spirit: 220,
    lives: 20,
    color: '#52B788',
    icon: 'lobby',
    desc: 'A wide-open lobby with one main hallway. Friendly intro map. Coffee bar in the corner.',
    path: [
      { x: -40, y: 220 }, { x: 320, y: 220 }, { x: 320, y: 420 },
      { x: 760, y: 420 }, { x: 760, y: 260 }, { x: 1080, y: 260 },
      { x: 1080, y: 560 }, { x: 1320, y: 560 },
    ],
    waves: 'standard',
  },
  {
    id: 'sanctuary',
    name: 'The Sanctuary',
    subtitle: 'do NOT disturb the sermon',
    difficulty: 2,
    unlocked: true,
    spirit: 200,
    lives: 15,
    color: '#3D5A80',
    icon: 'sanctuary',
    desc: 'Two aisles converge on the pulpit. Late arrivals come in HOT.',
    path: [
      { x: 200, y: -40 }, { x: 200, y: 300 }, { x: 460, y: 300 },
      { x: 460, y: 500 }, { x: 820, y: 500 }, { x: 820, y: 300 },
      { x: 1080, y: 300 }, { x: 1080, y: 840 },
    ],
    waves: 'sanctuary',
  },
  {
    id: 'fellowship',
    name: 'Fellowship Hall',
    subtitle: 'guard the casserole',
    difficulty: 3,
    unlocked: true,
    spirit: 240,
    lives: 18,
    color: '#F77F00',
    icon: 'fellowship',
    desc: 'Long folding tables. The food is the base. Potluck pirates everywhere.',
    path: [
      { x: -40, y: 360 }, { x: 240, y: 360 }, { x: 240, y: 180 },
      { x: 540, y: 180 }, { x: 540, y: 540 }, { x: 880, y: 540 },
      { x: 880, y: 180 }, { x: 1180, y: 180 }, { x: 1180, y: 480 }, { x: 1320, y: 480 },
    ],
    waves: 'fellowship',
  },
  {
    id: 'parking',
    name: 'The Parking Lot',
    subtitle: 'after-service traffic jam',
    difficulty: 4,
    unlocked: false,
    spirit: 180,
    lives: 12,
    color: '#1A1A1A',
    icon: 'parking',
    desc: 'Locked! Beat Fellowship Hall to unlock the chaos of post-service parking.',
    path: [],
    waves: 'standard',
  },
  {
    id: 'vbs',
    name: 'The Youth Lounge',
    subtitle: 'sugar rush hour',
    difficulty: 5,
    unlocked: false,
    spirit: 160,
    lives: 10,
    color: '#FF3D7F',
    icon: 'vbs',
    desc: 'Locked! VBS kids only. Bring your fastest friends.',
    path: [],
    waves: 'standard',
  },
];

// wave packs — { delay (s before wave), spawns: [{type, count, gap (s)}] }
const WAVES_STANDARD = [
  { name: 'The Early Birds', spawns: [{ type: 'late', count: 6, gap: 1.1 }] },
  { name: 'Bulletin Rush', spawns: [{ type: 'late', count: 8, gap: 0.9 }, { type: 'potluck', count: 3, gap: 1.4 }] },
  { name: 'Sugar Rush', spawns: [{ type: 'vbs', count: 12, gap: 0.55 }] },
  { name: 'Mixed Crowd', spawns: [{ type: 'late', count: 6, gap: 0.8 }, { type: 'asker', count: 3, gap: 1.6 }, { type: 'potluck', count: 5, gap: 1.0 }] },
  { name: 'Theological Inquiry', spawns: [{ type: 'asker', count: 8, gap: 1.3 }, { type: 'vbs', count: 8, gap: 0.6 }] },
  { name: 'Lunch Rush', spawns: [{ type: 'potluck', count: 14, gap: 0.7 }] },
  { name: 'The Committee Arrives', spawns: [{ type: 'asker', count: 6, gap: 1.0 }, { type: 'boss', count: 1, gap: 0 }, { type: 'late', count: 8, gap: 0.6 }] },
];

const WAVES_SANCTUARY = WAVES_STANDARD; // reuse for now
const WAVES_FELLOWSHIP = WAVES_STANDARD;

const WAVE_PACKS = {
  standard: WAVES_STANDARD,
  sanctuary: WAVES_SANCTUARY,
  fellowship: WAVES_FELLOWSHIP,
};

Object.assign(window, { DEFENDERS, ENEMIES, MAPS, WAVE_PACKS });
